# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c237926a56c04c1aa26864eaf0c442971a0ffabd8df03f8fdf11f7d2b5e985fea86e17951b940fb1767f5284b433c5403dc345c567f0ae61656410af115f90a

test:
  secret_key_base: 53542e704c2ed58cf3e7854f822d77b5910e2fa158b1940a7cba5a1b0ff3c9ea9e180aafa9165ecd30c76901b3963d6c2af6b50d3591979c80157e172311b7fa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
